spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
cipherchat.jwt.expiry-seconds=3600
cipherchat.refresh.expiry-seconds=1209600
cipherchat.crypto.master-key=${CIPHERCHAT_MASTER_KEY:dev-only-change-in-production}
cipherchat.allowed-origins=http://localhost:5173,http://localhost:8080,http://192.168.137.1:5173,http://192.168.137.1:8080,http://192.168.1.13:5173,http://192.168.1.13:8080,https://cipherchat-9rjy.onrender.com
management.endpoints.web.exposure.include=*
